# Generated by Django 5.2.1 on 2025-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagementSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('phone_number', models.IntegerField(max_length=11, verbose_name='Phone Number')),
                ('owner', models.CharField(max_length=120, verbose_name='Listed By')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('negotiate', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
            ],
        ),
    ]
