# Generated by Django 5.2.1 on 2025-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_propertymanagementrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='summary',
            field=models.CharField(default='Not Added', max_length=30, verbose_name='Short building tag'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='summary',
            field=models.CharField(default='Not Added', max_length=30, verbose_name='Short building tag'),
        ),
    ]
