# Generated by Django 5.2.1 on 2025-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_propertymanagementrent_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='summary',
            field=models.CharField(default=None, max_length=30, verbose_name='Short building tag'),
        ),
    ]
