# Generated by Django 5.2.1 on 2025-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_propertymanagementsale_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='summary',
            field=models.CharField(default=None, max_length=30, verbose_name='Short building tag'),
        ),
    ]
