# Generated by Django 5.2.1 on 2025-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_alter_propertymanagementrent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='Landlord'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='Landlord'),
        ),
    ]
