# Generated by Django 5.2.1 on 2025-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_propertymanagementrent_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
