# Generated by Django 5.2.1 on 2025-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_propertymanagementrent_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent/'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy/'),
        ),
    ]
