# Generated by Django 5.2.1 on 2025-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_remove_propertymanagementrent_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementsale',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
