# Generated by Django 5.2.1 on 2025-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_propertymanagementsale_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='whilist',
            field=models.BooleanField(default=False, verbose_name='Add to Whilist'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='whilist',
            field=models.BooleanField(default=False, verbose_name='Add to Whilist'),
        ),
    ]
