# Generated by Django 5.2.1 on 2025-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_remove_salepropertyimage_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='owner',
            field=models.CharField(default='Akinfiresoye', max_length=120, verbose_name='Listed By'),
        ),
    ]
