# Generated by Django 5.2.1 on 2025-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_alter_propertymanagementsale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy'),
        ),
    ]
