# Generated by Django 5.2.1 on 2025-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0018_alter_propertymanagementrent_base_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='price_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
