# Generated by Django 5.2.1 on 2025-06-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0019_alter_propertymanagementrent_price_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='price_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
