# Generated by Django 5.2.1 on 2025-06-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_auto_20250627_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='price_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
